{% set name = "QuantLib-python" %}
{% set version = "1.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lballabio/QuantLib-SWIG/releases/download/v{{ version }}/QuantLib-SWIG-{{ version }}.tar.gz
  sha256: fa31023207937616ca0f880eda774b6a2273ba6274e776ee9bf631ddc6bf54b8
  patches:
    # Prevent python-build from creating an isolated venv and pulling deps from PyPI.
    - patches/no-isolation.diff  # [unix]

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - swig
  host:
    - python
    - setuptools
    - pip
    - wheel
    - python-build  # [unix]
    - libboost-devel
    - quantlib {{ version }}
  run:
    - python
    - quantlib

test:
  imports:
    - QuantLib
  source_files:
    - Python/test/*
  commands:
    - python Python/test/QuantLibTestSuite.py

about:
  home: https://github.com/lballabio/QuantLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The python wrapper of QuantLib.
  description: |
    The QuantLib project (https://www.quantlib.org) is aimed at providing 
    a comprehensive software framework for quantitative finance. QuantLib 
    is a free/open-source library for modeling, trading, and risk management 
    in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib-SWIG

extra:
  recipe-maintainers:
    - timkpaine
